<?
$MESS["LANDING_CMP_TITLE"] = "Strony";
$MESS["LANDING_CMP_MODULE_NOT_INSTALLED"] = "Usługa Bitirix24.Sites jest obecnie niedostępna.";
$MESS["LANDING_CMP_ACCESS_DENIED"] = "Usługa Bitirix24.Sites jest obecnie dostępna tylko dla administratorów.";
$MESS["LANDING_CMP_AGREEMENT_NAME"] = "Bitrix24.Sites Regulamin użytkowania";
$MESS["LANDING_CMP_AGREEMENT_TEXT"] = "<p>Bitrix24.Sites dostarcza usługi, za pomocą umożliwiające tworzenie stron internetowych i strony docelowe dla swojej firmy, klientów lub do użytku osobistego. Wszelkie strony internetowe lub docelowe muszą być zgodne z prawem kraju, w którym są tworzone.<p>Zastrzegamy sobie prawo do zamknięcia witryny bez powiadomienia w przypadku wykrycia jakiegokolwiek naruszenia (w wyniku dochodzenia wewnętrznego, skargi użytkownika lub zawiadomienia od strony trzeciej).</p><p>Zasady są proste. Musisz posiadać lub mieć pozwolenie na treści publikowane w witrynie lub na stronie docelowej i postępować zgodnie z wszystkimi obowiązującymi przepisami. 123_4_5_321 |<p>Klikając przycisk &laquo;Akceptuję regulamin&raquo, zobowiązujesz się:</p><ul>
<li>Szanować prawa własności intelektualnej oraz przepisy dotyczące reklamy i marketingu oraz inne przepisy prawne obowiązujące w kraju (zwane dalej Obowiązującym Prawem) w okresie korzystania z usług Bitrix24.Sites.
<li>Dopilnować, aby informacje, dokumentacja i inne elementy (zwane dalej Treściami) publikowane na stronie internetowej utworzonej za pomocą usług Bitrix24.Sites nie naruszały praw własności intelektualnej ani znaków towarowych stron trzecich; nie ujawniać poufnych informacji biznesowych; nie szkodzić reputacji stron trzecich; nie naruszać obowiązującego prawa.
<li>W razie jakichkolwiek wątpliwości odnośnie wykorzystania Treści na swojej stronie internetowej przed publikacją uzyskać profesjonalną poradę od firmy prawniczej.
<li>Wszelkie treści publikowane lub przeznaczone do publikacji za pośrednictwem usług Bitrix24.Sites zostały uzyskać zgodnie z obowiązującym prawem.
<li>Uznać, że z usług Bitrix24.Sites korzysta się na własne ryzyko.
<li>Uznać i potwierdzić, że Bitrix Inc. nie tworzy stron ani serwisów internetowych; w żaden sposób nie modyfikuje treści publikowanych za pomocą usług Bitrix24.Sites; nie zachęca użytkowników do publikowania treści; nie ma i nie powinna mieć żadnej wiedzy o możliwym naruszeniu Obowiązującego Prawa.</ul><p>
Bitrix Inc. zastrzega sobie prawo do zamknięcia stron internetowych użytkownika i /lub odebrania dostępu do usług Bitrix24.Sites w przypadku naruszenia powyższych postanowień.</p><p>Całość Regulaminu korzystania z Bitrix24, patrz<a href=\"https://www.bitrix24.com/terms/\">Regulamin świadczenia usług</a>.</p>";
?>