<?
$MESS ['FS_ERROR1'] = "ข้อมูลที่ใช้ในการค้นหาผิดพลาด:";
$MESS ['FS_ERROR2'] = "โปรดแก้ไขข้อมูลที่ใช้ในการค้นหาให้ถูกต้อง และลองใหม่";
$MESS ['FS_SYNTAX1'] = "ค้นหาข้อมูลประโยค:";
$MESS ['FS_SYNTAX2'] = "A common search query consists of one or more words: <br>	<i>contact information</i><br>This search query will find pages containing both query words. <br><br>Logical operators allow building more sophisticated queries, for example: <br> <i>contact information or phone</i><br>This search query will find pages containing either both &quot;contact&quot; and &quot;information&quot; words or &quot;phone&quot; word.<br><br> <i>contact information not phone</i><br>This search query will find pages containing either both &quot;contact&quot; and &quot;information&quot; words but not &quot;phone&quot;.<br>You can also use brackets to build even more sophisticated queries.<br><br> <b>Logical operators:</b> <table border=\"0\" cellpadding=\"5\"><tr><td align=\"center\" valign=\"top\"><font class=\"text\">Operator</font></td><td valign=\"top\"><font class=\"text\">Synonims</font></td><td><font class=\"text\">Description</font></td></tr><tr><td align=\"center\" valign=\"top\"><font class=\"text\">and</font></td><td valign=\"top\"><font class=\"text\">and, &, +</font></td><td><font class=\"text\">The <i>logical &quot;and&quot;</i> operator is implied and can be omitted: the query &quot;contact information&quot; is equivalent to the query &quot;contact and information&quot;.</font></td></tr><tr><td align=\"center\" valign=\"top\"><font class=\"text\">or</font></td><td valign=\"top\"><font class=\"text\">or, |</font></td><td><font class=\"text\">The <i>logical &quot;or&quot;</i> operator entails product search containing at least one of the operands. </font></td></tr><tr><td align=\"center\" valign=\"top\"><font class=\"text\">not</font></td><td valign=\"top\"><font class=\"text\">not, ~</font></td><td><font class=\"text\">The <i>logical &quot;not&quot;</i> operator limits the search to pages not containing the operand. </font></td></tr><tr><td align=\"center\" valign=\"top\"><font class=\"text\">( )</font></td><td valign=\"top\"><font class=\"text\">&nbsp;</font></td><td><font class=\"text:\"><i>Round brackets</i> define the logical operator execution sequence. </font></td></tr></table>";
$MESS ['FS_RESULTS'] = "ผลลัพธ์การค้นหา";
$MESS ['FS_SEARCH'] = "ค้นหา";
$MESS ['FS_NO_RESULTS'] = "การค้นหาของคุณไม่ตรงกับเอกสารใดเลย  ทดลองคีย์เวิร์ดอื่น";
$MESS ['SEARCH_TITLE'] = "ค้นหา";
$MESS ['KEYWORDS'] = "คีย์เวิร์ค";
$MESS ['SEARCH_FORUMS'] = "ค้นหาเว็บบอร์ด";
$MESS ['ALL_FORUMS'] = "เว็บบอร์ดทั้งหมด";
?>